@all @internal @view_cases
Feature: I want to view the case details of a case
  As a Logged in government user
  I want to view the details on a case
  So that I can make review the case before making any decisions

@regression
  Scenario: View a standard trade control application
    Given I sign in to SSO or am signed into SSO
    And a standard trade control application is created
    When I go to the case list page
    Then I should see my case in the cases list
    And I should see my case SLA
    When I go to the case
    Then I see the case page
    When I go to the documents tab
    Then I see my autogenerated application form

@regression
Scenario: View an open trade control application
  Given I sign in to SSO or am signed into SSO
  And an open trade control application is created
  When I go to the case list page
  Then I should see my case in the cases list
  And I should see my case SLA
  When I go to the case
  Then I see the case page
  When I go to the documents tab
  Then I see my autogenerated application form
