from form.helpers import Section, Form, Question, InputType

section1 = Section("Register a Business", "", [
    Form("Register a Business", "Lorem Ipsum", [
        Question(title='What\'s the business name?',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
        Question(title='EORI number',
                 description='',
                 input_type=InputType.INPUT,
                 name='eori_number'),
        Question(title='SIC number',
                 description='',
                 input_type=InputType.INPUT,
                 name='sic_number'),
        Question(title='VAT number',
                 description='',
                 input_type=InputType.INPUT,
                 name='vat_number'),
        Question(title='Address',
                 description='',
                 input_type=InputType.INPUT,
                 name='address'),
        Question(title='The email of the admin user',
                 description='',
                 input_type=InputType.INPUT,
                 name='admin_user_email'),
    ]),
])
