from form.helpers import Section, Form, Question, InputType, ArrayQuestion, Option

section1 = Section("Register a Business", "", [
    Form("Form Title", "Form Description", [
        Question(title='What\'s the business name?',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
        Question(title='EORI number',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
        Question(title='SIC number',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
        Question(title='VAT number',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
        Question(title='Address',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
        Question(title='The email of the admin user',
                 description='',
                 input_type=InputType.INPUT,
                 name='name'),
    ]),
])
