version: '3'

services:
  govfedb:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=password
    expose:
      - 5432
    ports:
      - 5431:5432
    networks:
      - lite-api_default

  govfe:
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - govfedb
    expose:
      - 8080
    networks:
      - lite-api_default
    command: pipenv run gunicorn -c gconfig.py conf.wsgi
#    command: pipenv run ./manage.py runserver 0.0.0.0:8080

networks:
  lite-api_default:
    external: true
