# Generated by Django 2.2.2 on 2019-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_token",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
