pipeline
        {
          agent {
             node {
                label env.CI_SLAVE
             }
          }
            parameters
            {
                // Define DRIVER parameter for running the test
                choice(name: 'DRIVER', description: 'Choose browser', choices: 'chrome\nfirefox\nheadless')

                // Define test path to run
                string(name: 'TESTS_TO_RUN', defaultValue: '', description: 'choose test to run, leave blank to run all tests')

                // Define environment to run tests on
                choice(name: 'ENVIRONMENT', description: 'choose what environment to run in', choices: 'staging\ndev\nuat')

                //Define branch to run
                string(name: 'BRANCH', defaultValue: 'master', description: 'choose branch to run against')
            }

            options
            {
                // keep last 100 builds
                buildDiscarder(logRotator(numToKeepStr: '10'))

                // add timestamp
                timestamps()
            }

            // agent any // run the pipeline on any available node
            stages
            {
                stage('SCM: code update')
                {
                    steps
                    {
                        // checking out repository
                        checkout([
                                $class: 'GitSCM', branches: [[name: "${params.BRANCH}"]],
                                userRemoteConfigs: [[url: 'https://github.com/uktrade/lite-internal-frontend.git']]
                        ])

                        // Create Allure report folders and grant relevant permissions
                        sh "mkdir -p ./ui_automation_tests/allure-results"
                        // sh "rm -rf ./ui_automation_tests/allure-results/*"
                        // sh "chown jenkins:jenkins ./ui_automation_tests/allure-results"
                    }
                }
                stage('Docker build')
                {
                    steps
                    {
                        script
                        {
                            // building selenium base
                            docker.build("exporter/selenium_base", "-f ui_automation_tests/selenium-base-image/Dockerfile --network host ui_automation_tests/selenium-base-image")

                            // building selenium image
                            test = docker.build("exporter/selenium_image", "-f ui_automation_tests/selenium-automation-run/Dockerfile --network host ui_automation_tests")
                        }
                    }
                }
                stage('Run test')
                {
                    steps
                    {
                        script
                        {
                            // creating timestamp
                            def now = new Date()
                            tstamp = now.format("yyyyMMdd-HH:mm:ss.SSSS", TimeZone.getTimeZone('UTC'))

                            // running selenium tests using pytest via docker
                            test.inside("--network host --privileged --shm-size=1g -e PYTHONPATH=${env.WORKSPACE} -e ENVIRONMENT=${params.ENVIRONMENT} -w=${env.WORKSPACE}/ui_automation_test --entrypoint=''") {
                                    sh "/docker-entry.sh ${params.TESTS_TO_RUN}"


                        }
                    }
                }
            }
            post
            {
                always
                {
                    // Generate Allure Report
                    generateAllureReport()
                }
            }
        }

// Generate Allure report function
def generateAllureReport()
    {
        try
        {
            allure([
                    commandline      : '2.5.0',
                    includeProperties: false,
                    jdk              : '',
                    properties       : [[key: 'allure.tests.management.pattern', value: 'http://tms.company.com/%s']],
                    reportBuildPolicy: 'ALWAYS',
                    results          : [[path: 'ui_automation_tests/allure-results']]
            ])
        }
        catch (error)
        {
            error.message
        }
    }
